### ISSUE TITLE
Update the link for emscripten in docs

### ISSUE THREAD

**Issue by m3ndi** [bgrins/videoconverter.js#22]
https://bgrins.github.io/videoconverter.js/#build

Currently the link points to 
https://github.com/kripken/emscripten/wiki/Tutorial
There said the the link soon will be deleted so please change it to:
http://kripken.github.io/emscripten-site/docs/getting_started/Tutorial.html

Thanks for great product!

**Comment by bgrins** [comment]
Updated the link - thanks for the heads up
