### ISSUE TITLE
Live Video Streaming

### ISSUE THREAD

**Issue by acefxlabs** [bgrins/videoconverter.js#28]
After i discovered videoconverter.js i was of the idea of building an app like livestream procatser for a client.
Is it possible to stream video as normally done via ffmpeg

Thanks

**Comment by bgrins** [comment]
I'm not sure I get the use case you are thinking of.  But ffserver and networking are disabled in the configuration, so it most likely won't work.

**Comment by acefxlabs** [comment]
Okay to be more clearer, i can stream live video via FFMPEG, is that possible with videoconveter,js

**Comment by bgrins** [comment]
You mean send a stream from an input in the browser (like a webcam)?

**Comment by acefxlabs** [comment]
Actually from a mobile app using the phone camera

**Comment by bgrins** [comment]
I don't think this will work for that, sorry
