### ISSUE TITLE
Compiling problem with recent emscripten (1.29.4 or 1.31.0)

### ISSUE THREAD

**Issue by duanyao** [bgrins/videoconverter.js#29]
@bgrins Which version of emscripten can successfully build current videoconverter.js?

I try to build this project with emscripten 1.29.4 or 1.31.0 on linux, but encountered a few problems (using `build_lgpl.sh`), and I didn't find a solution to the last one.
1. zlib build error
   Building of zlib generated this error:
   
   `ERROR    root: adler32.lo: Input file has an unknown suffix, don't know what to do with it!`
   
   It seems we have to add `--static` to `configure` of zlib. Recently emscripten started to support shared library, and `configure` of zlib detected this and enabled shared library build. However, shared library build of zlib uses `.lo` file, which is not supported by emscripten, so the build failed. So we have to add `--static` to enforce static build.
2. ffmpeg build error
   When emmake  ffmpeg:
   
   ```
   libavformat/segment.c:694:13: error: implicit declaration of function
       'localtime_r' is invalid in C99
       [-Werror,-Wimplicit-function-declaration]
             localtime_r(&sec, &ti);
   ```
   
   It seems we may define `-D_XOPEN_SOURCE=600` before `configure` of ffmpeg to make such code compile:
   
   ```
   CPPFLAGS="-D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600" emconfigure ./configure --cc="emcc" --prefix=$(pwd)/../dist --enable-cross-compile --target-os=none --arch=x86_32 --cpu=generic \
   --disable-ffplay --disable-ffprobe --disable-ffserver --disable-asm --disable-doc --disable-devices --disable-pthreads --disable-w32threads --disable-network \
   --disable-hwaccels --disable-parsers --disable-bsfs --disable-debug --disable-protocols --disable-indevs --disable-outdevs --enable-protocol=file
   ```
3. ffmpeg.js build error
   When excuting
   `emcc -s OUTLINING_LIMIT=100000 -s VERBOSE=1 -s TOTAL_MEMORY=33554432 -O2 -v ffmpeg.bc -o ../ffmpeg.js --pre-js ../ffmpeg_pre.js --post-js ../ffmpeg_post.js`
   
   Error is thrown:
   
   ```
   AssertionError: Error in optimizer: Assertion failed: undefined
   
   events.js:72
       throw er; // Unhandled 'error' event
             ^
   Error: write EPIPE
   at errnoException (net.js:901:11)
   at Object.afterWrite (net.js:718:19)
   
   events.js:72
       throw er; // Unhandled 'error' event
             ^
   Error: write EPIPE
   at errnoException (net.js:901:11)
   at Object.afterWrite (net.js:718:19)
   ```

**Comment by bgrins** [comment]
Hi, it was built with commit df11c6f1fd1636a355b83a1c48b3a890596e6a32 (https://github.com/bgrins/videoconverter.js/blob/42def8c4136b03cbe55951fbf6fcda214f51059a/build/build_all_codecs.sh#L1).

If you are able to make the changes you suggest and get it to compile with the latest release, that'd be great.  I have a work in progress locally where I started this process, but you seem to be onto some of the fixes already.

Regarding the error with the final `emcc`, try removing OUTLINING_LIMIT.  I saw a similar error and filed: https://github.com/kripken/emscripten/issues/3297.  But it should work fine without the outlining change.

**Comment by duanyao** [comment]
Strange, the third error disappeared after I rebuilt emscripten 1.31.0 and built videoconverter.js again. Now at least `build_lgpl.sh` works. Thanks!

**Comment by bgrins** [comment]
Oh, nice!  I'd be very interested in seeing the changes you needed to make to the build scripts.  Could you send a PR over?

**Comment by duanyao** [comment]
Sure.

However, x264 still failed to build by 1.31.0 , error message is `endian test failed`.

**Comment by bgrins** [comment]
Thanks!  Moving discussion over to #30
