### ISSUE TITLE
How to cut videos ? 

### ISSUE THREAD

**Issue by sheikhasadmuneer** [bgrins/videoconverter.js#35]
i want to cut video i.e ( extract part from a video ) 
on cmd it works fine but on your given terminal it doesnt 

i use below command to cut video in cmd .
$cmd =  "ffmpeg -ss $start  -t $end -i $video video/cut".$i.".mp4"; // for cutting video 

i tried this commad
 -ss 0  -t  5  -i  input.webm samp.webm
 on the demo link
http://bgrins.github.io/videoconverter.js/demo/

it gives the file but the file doesnt have any video  ,Need help regarding this Thanks,

**Comment by bgrins** [comment]
You can see the problem by looking at the the log in the output for the command - you need to add '-strict -2' to the command.  Check out the 'H.264' or 'VP9' buttons on the demo app, which do something really similar.

**Comment by sheikhasadmuneer** [comment]
Thanks Alot mate , it worked :))
