### ISSUE TITLE
Progress information

### ISSUE THREAD

**Issue by indianakernick** [bgrins/videoconverter.js#38]
Everything works fine but the progress info is outputs via stderr AS A SINGLE MESSAGE when the operation has completed. That's not very useful! The progress info should output as it happens. Is there an argument that will fix this? Or a Module property?

**Comment by indianakernick** [comment]
@bgrins have you abandoned this project?!

**Comment by bgrins** [comment]
Hi, output timing is dependent on ffmpeg's behavior.  See http://bgrins.github.io/videoconverter.js/demo/ with the 'video to mp4' demo which uses `-vf showinfo` argument so progress is shown as it happens.

**Comment by indianakernick** [comment]
That worked! Thank you @bgrins 👍🏼
